apiVersion: v1
kind: Service
metadata:
  name: calc-service
  labels:
    app: calcapp
spec:
  type: NodePort
  selector:
    app: calcapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
