apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: calcapp
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: calcapp
  template:
    metadata:
      labels:
        app: calcapp
    spec:
      containers:
        - name: mynode
          image: stephhl/calcapp:latest
          ports:
            - containerPort: 8080
