apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: calcapp
spec:
  containers:
    - name: nodewebapp
      image: stephhl/calcapp:latest
      ports:
        - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
